# netlify.toml (VERSIÓN FINAL Y SIMPLIFICADA)

# Solo le decimos a Netlify dónde están nuestras funciones y cómo programarlas.
# No definimos NADA sobre la construcción (build) o publicación (publish),
# para que Netlify use sus valores por defecto, que son correctos para tu proyecto.

[functions]
  directory = "netlify/functions/"

[functions."daily-notification"]
  schedule = "* * * * *" # Recuerda cambiar esto a "0 9 * * *" cuando termines de probar