# netlify.toml (VERSIÓN CORRECTA Y SIMPLIFICADA)

# Define la configuración para una función específica llamada "daily-notification"
[[functions]]
  # El nombre del archivo de tu función (sin la extensión .js)
  name = "daily-notification" 
  
  # La programación cron para que se ejecute cada minuto (para pruebas)
  schedule = "* * * * *"